### ISSUE TITLE
Can adgcl be used on single graph for  node-level task?

### ISSUE THREAD

**Issue by scottshufe** [susheels/adgcl#5]
Hi, thanks for your excellent work!
I find that you evaluate adgcl mainly on graph-level task with multiple datasets. And I wonder whether adgcl can be applied on a single graph dataset like Cora or Citeseer for node classification?

**Comment by susheels** [comment]
Hi. Thanks for checking our work. Yes, AD-GCL in principle can be applied to node classification settings also. 
In its current instantiated form, we don't perform node-level tasks and it is worthy of future study.

**Comment by scottshufe** [comment]
Thanks for your quick reply! I'll try it.
